apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vps-landing-app
    sha: d0e137220d7ff58d0ef634a82693f5c04cce16aa
    version: 1.0.0
  name: vps-landing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vps-landing-app
      version: 1.0.0
  template:
    metadata:
      labels:
        app: vps-landing-app
        version: 1.0.0
    spec:
      containers:
        - image: docker.io/nikhil12894/myvps_landing:latest
          name: vps-landing-container
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vps-landing-app
    version: 1.0.0
  name: vps-landing-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: vps-landing-app
    version: 1.0.0
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt
  labels:
    app: vps-landing-app
    version: 1.0.0
  name: vps-landing-ingress
  namespace: default
spec:
  ingressClassName: public
  rules:
    - host: learnwithnk.in
      http:
        paths:
          - backend:
              service:
                name: vps-landing-service
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - learnwithnk.in
      secretName: vps-landing-tls
