apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vps-landing-app
    sha: ade75469ec6dbd39bdc18a031d7a7372c2586117
    version: 1.0.0
  name: vps-landing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vps-landing-app
      version: 1.0.0
  template:
    metadata:
      labels:
        app: vps-landing-app
        version: 1.0.0
    spec:
      containers:
      - image: docker.io/nikhil12894/vps-landing:v1.0.1
        name: vps-landing-container
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vps-landing-app
    version: 1.0.0
  name: vps-landing-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: vps-landing-app
    version: 1.0.0
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    # kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: lets-encrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  labels:
    app: vps-landing-app
    version: 1.0.0
  name: vps-landing-ingress-1
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: explorewithnk.com
    http:
      paths:
      - backend:
          service:
            name: vps-landing-service
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - explorewithnk.com
    secretName: vps-landing-tls-1
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   annotations:
#     kubernetes.io/ingress.class: public
#     cert-manager.io/cluster-issuer: lets-encrypt-prod
#   labels:
#     app: vps-landing-app
#     version: 1.0.0
#   name: vps-landing-ingress-2
#   namespace: default
# spec:
#   ingressClassName: public
#   rules:
#   - host: learnwithnk.in
#     http:
#       paths:
#       - backend:
#           service:
#             name: vps-landing-service
#             port:
#               number: 80
#         path: /
#         pathType: Prefix
#   tls:
#   - hosts:
#     - learnwithnk.in
#     secretName: vps-landing-tls-1
