apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: editor-root-app
    sha: 7cef08465dbcaecbce913ebd7af2c444e86a8e8e
    version: 1.0.0
  name: editor-root
spec:
  replicas: 1
  selector:
    matchLabels:
      app: editor-root-app
      version: 1.0.0
  template:
    metadata:
      labels:
        app: editor-root-app
        version: 1.0.0
    spec:
      containers:
        - image: docker.io/nikhil12894/editor-app:v1.0.0
          name: editor-root-container
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: editor-root-app
    version: 1.0.0
  name: editor-root-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: editor-root-app
    version: 1.0.0
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt
  labels:
    app: editor-root-app
    version: 1.0.0
  name: editor-root-ingress
  namespace: default
spec:
  ingressClassName: public
  rules:
    - host: app-editor.learnwithnk.in
      http:
        paths:
          - backend:
              service:
                name: editor-root-service
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - app-editor.learnwithnk.in
      secretName: editor-root-tls
