apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: editor-root-app
    sha: f11c98f3aa486250e2de813f65c2bb6f6db3a639
    version: 1.0.0
  name: editor-root
spec:
  replicas: 1
  selector:
    matchLabels:
      app: editor-root-app
      version: 1.0.0
  template:
    metadata:
      labels:
        app: editor-root-app
        version: 1.0.0
    spec:
      containers:
        - image: docker.io/nikhil12894/editor-app:v1.0.2
          name: editor-root-container
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: editor-root-app
    version: 1.0.0
  name: editor-root-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: editor-root-app
    version: 1.0.0
  type: ClusterIP
