# dashy-argocd-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dashy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://vyrtualsynthese.github.io/selfhosted-helmcharts/
    targetRevision: "1.0.0" # Replace with the correct version
    chart: dashy
    helm:
      values: |
        ingress:
          enabled: true
          hosts:
          - host: dashy.learnwithnk.in # Replace with your domain
            paths:
            - path: /
              pathType: prefix
          annotations:
            kubernetes.io/ingress.class: public
            cert-manager.io/cluster-issuer: lets-encrypt-prod
            # kubernetes.io/tls-acme: true
          tls:
          - hosts:
            - dashy.learnwithnk.in
            secretName: dashy-tls-cert
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
